apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: seven-wonders-prometheus-monitor
  namespace: seven-wonders
  labels:
    # this label is used by prometheus-operator to find ServiceMonitors
    release: prometheus-operator
spec:
  endpoints:
    - interval: 3s
      path: /actuator/prometheus
      port: 80-80
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: seven-wonders
